CREATE OR REPLACE FUNCTION `pi-dashboard-398109.datamart.fiscal_year`(Month DATE) RETURNS STRING AS (
(
    SELECT
      CASE
        WHEN EXTRACT(MONTH FROM  DATE(Month)) BETWEEN 4 AND 6 THEN CONCAT(1 + EXTRACT(YEAR FROM  DATE(Month)),".Q1") --1Qの期間を指定
        WHEN EXTRACT(MONTH FROM  DATE(Month)) BETWEEN 7 AND 9 THEN CONCAT(EXTRACT(YEAR FROM  DATE(Month)),".Q2") --2Qの期間を指定
        WHEN EXTRACT(MONTH FROM  DATE(Month)) BETWEEN 10 AND 12 THEN CONCAT(EXTRACT(YEAR FROM  DATE(Month)),".Q3") --3Qの期間を指定
        WHEN EXTRACT(MONTH FROM  DATE(Month)) BETWEEN 1 AND 3 THEN CONCAT(EXTRACT(YEAR FROM  DATE(Month)),".Q4") --4Qの期間を指定
      END
  )
);
